---
- name: Install master Jenkins
  hosts: local-dev
  connection: local
  become: yes

  pre_tasks:
  - name: update apt if needed
    apt: update_cache=yes

  roles:
    - geerlingguy.git
    - geerlingguy.java
    - role: gantsign.maven
      maven_download_timeout: 300

    - geerlingguy.jenkins
    - andrewrothstein.terraform